### PR TITLE
v3 blog post draft

### PR DESCRIPTION
**Pull request by ryanseddon**
Draft post!

Todo:
- [x] Link up contributor names
- [ ] Update date in filename to match publish date
- [x] backtick all the correct bits, got lost in the copy paste job

### CODE REVIEW

**Comment by paulirish** [comment]
post is lookin goood

**Comment by ryanseddon** [comment]
Ok everything is fixed and all we need to do is change the file date when we're ready to :shipit:

**Comment by SlexAxton** [comment]
:tada:

**Comment by patrickkettner** [comment]
sorry for being so quiet - theres are a couple builder bugs ive been trying
to work out. The checkboxes can get out of sync on the middle screen and
small screen views, and the "add/remove" all button is broken when using
all packages. then :+1:

On Sun, Aug 30, 2015 at 3:44 PM, Alex Sexton <notifications@github.com>
wrote:

> [image: :tada:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/modernizr-neue/pull/9#issuecomment-136186502>
> .
>



-- 
patrick

**Comment by patrickkettner** [comment]
closing as a result of f8a314cf0b759db32c61406d601248ad1b139961

**Pull request closed without merging**
