### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by ryanseddon**
- Made all components use pure render mixin so static components don’t re-render
- Added active state to nav
- Added ternary helper handlebars templates
- Removed aliasify as uglify has dead code removal

### CODE REVIEW

**Comment by patrickkettner** [comment]
The `aliasify` code was to remove dead code from react itself. when I tested it, it was _much_ smaller when using it - did you compare the filesize?

**Comment by patrickkettner** [comment]
with aliasify
```
$) ls -la dist/js/prod.js
-rw-r--r-- 1 pdk 183046 May 16 13:04 dist/js/prod.js
```

without it
```
$) ls -la dist/js/prod.js
-rw-r--r-- 1 pdk 222210 May 16 13:05 dist/js/prod.js
```

a 40k difference

**Comment by patrickkettner** [comment]
I didn't know about the `PureRenderMixin` - that seems super neat!

Based on what I am reading it seems like it does a `shouldComponentUpdate` on the entire state and prop. Since we are already doing that but with a single prop instead, is the perf still better for one of the more used components like detect (searching for gibberish is how I usually tested this)?

**Comment by ryanseddon** [comment]
Hmm that weird can't seem to figure out why uglify isn't removing all of reacts development code. The webpack build I use at work does this fine, I'll revert for now.

**Comment by patrickkettner** [comment]
thinking about it more, its not dead code, its debugging code. stuff like improved log messaging. It will be used, it just doesn't need to be

**Comment by ryanseddon** [comment]
Yeah but in theory all the `'production' !== process.env.NODE_ENV` should be rewitten to `'production' !== 'production'` for the prod build which is false which to uglify is a dead code path.

**Comment by ryanseddon** [comment]
Ok we should be good now, we're about ~3kb diff on gzip size.

**Comment by patrickkettner** [comment]
did you get a chance to check `PureRenderMixin` is improving the rendering perf (since I _think_ we were already doing what it does automagically, just with a smaller dataset for comparison)?

**Comment by ryanseddon** [comment]
Ah yep forgot about that:

So heres a perf test as is without the `PureRenderMixin`:

modernizr-neue

And this PR with `PureRenderMixin`:

modernizr-neue purerender

Both breakdowns this PR does less:

screen shot 2015-05-19 at 14 27 04

**Comment by patrickkettner** [comment]
b-e-a-utiful.

**Comment by SlexAxton** [comment]
<3z

**Comment by paulirish** [comment]
v nice!

**Pull request merged**
