### PR TITLE
Add build tracking on Build button click

### PR DESCRIPTION
**Pull request by KuraFire**
This should suffice, but I can’t test locally since the build script isn’t working properly (on my Mac).

### CODE REVIEW

**Comment by patrickkettner** [comment]
In what way is the build script nor working?

**Comment by KuraFire** [comment]
@patrickkettner Nodemon keeps restarting "due to changes" but it's causing the changes itself due to doing a build. It's an endless loop of "build files, start server, restart server due to files changed".

**Comment by patrickkettner** [comment]
That should happen a few times during the initial build. How long did you
wait?

**Comment by KuraFire** [comment]
It was an endless loop, like, I saw it repeating itself at least 50 times.

**Comment by KuraFire** [comment]
For anyone who's not having issues: to test whether this works, pull this branch and see if it triggers a GAnalytics pageview event upon clicking Build, and the pageview should have the format of `/build/testname^anothertestname^athirdtestname`.

**Comment by ryanseddon** [comment]
Yeah I get this loop to but it settles down after a while and I can test locally.

**Comment by ryanseddon** [comment]
So the GA api is different now I've update the PR. Tested locally and this works.

screen shot 2015-09-14 at 14 29 18

**Comment by KuraFire** [comment]
Okay, so is there any reason remaining for us not to merge this right now? Looks good to me, so :shipit:!

**Comment by KuraFire** [comment]
(ps Thanks @ryanseddon !)

**Pull request merged**
