### PR TITLE
try to publish at modernizr.com

### PR DESCRIPTION
**Pull request by paulirish**
worth a shot..

### CODE REVIEW

**Comment by paulirish** [comment]
failed. 

image

**Comment by paulirish** [comment]
reverted.

**Comment by paulirish** [comment]
got in touch with Patrick. he said he'd fix it up tonight.

**Comment by rejas** [comment]
If I had one wish from Googles Santa Claus, it would be to have Patrick for one day back at the Modernizr infrastructure ;-)

**Comment by rejas** [comment]
@paulirish could you get in touch with patrick one more time? people are opening bug reports which indicates that they are still using the site/service: https://github.com/Modernizr/Modernizr/issues/2490

**Pull request merged**
