### PR TITLE
Added property name to metadata - refs #66

### PR DESCRIPTION
**Pull request by joecritch**
This adds the property name in a `<code />` element, next to the detect title. This gives the benefit of not having to look up or guess the property when writing CSS or JS.

Refs #66

### CODE REVIEW

**Comment by patrickkettner** [comment]
could you screenshot it real quick?

**Comment by joecritch** [comment]
Sure, here you go.

pull-67-modernizr-neue

**Comment by patrickkettner** [comment]
do you think its clear without a label explaining what that means?

On Thu, Dec 17, 2015 at 3:00 AM, Joe Critchley <notifications@github.com>
wrote:

> Sure, here you go.
>
> [image: pull-67-modernizr-neue]
> <https://cloud.githubusercontent.com/assets/24449/11868086/4a1ae978-a4ad-11e5-9df7-646864751c8c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/modernizr-neue/pull/67#issuecomment-165422592>
> .
>



-- 
patrick

**Comment by ryanseddon** [comment]
Maybe we could have `Modernizr.<name>` and `.<name>`

**Comment by stucox** [comment]
Or even something like

**Usage:**
```js
if (Modernizr.history) {
  // supported
}
else {
  // not supported
}
```

Which would allow us to call out async detects as:

```js
Modernizr.on('history', function (result) {
  if (Modernizr.history) {
    // supported
  }
  else {
    // not supported
  }

**Comment by joecritch** [comment]
I think we should separate the concern of what the alias is vs. how to use it. Perhaps a progressive "?" help icon next to it that, when clicked, opens up usage examples with that alias in context?

**Comment by patrickkettner** [comment]
@stucox I think the usage is a great idea, but not for this specific issue. It means the user looses a lot of the scan ability
@joecritch :+1:

still not sure about how to show this the right way :/

**Comment by stucox** [comment]
Lateral thought:

Maybe the property name (`history`) should replace the title ("History API"), then the description could immediately follow (no need for a "Description" title) — and we make sure the first sentence of each description makes it very clear exactly what the detect does; preferably followed by a paragraph break.

**Comment by patrickkettner** [comment]
would we change what shows on the main list?

**Comment by joecritch** [comment]
— Made the property name into its own "Usage" box in the right-hand bar
— Added some basical modal functionality when you click "View examples"
— When `async` is true, it'll show a different JS example

screen shot 2016-01-27 at 15 08 38

**Comment by patrickkettner** [comment]
looks great! 

re syntax hihglighting, it shoulnd't need any kind of library at all. its all static content that is the same across all examples (as far as structure goes). We just need to pick a color scheme and add the proper classes to each element on the examples, right?

**Comment by joecritch** [comment]
Good idea!

- Added syntax highlighting
- Improved code indent on async examples
- Moved all CSS to stylesheets

screen shot 2016-01-28 at 13 47 44

**Comment by patrickkettner** [comment]
Looks awesome! Do it to it

**Comment by joecritch** [comment]
@patrickkettner merged to master, but it doesn't seem to have been deployed. might be related to #72

**Comment by patrickkettner** [comment]
There is an issue with detects with multiple properties

image

**Pull request merged**
