### PR TITLE
Replace node-zopfli with imagemin-zopfli

### PR DESCRIPTION
**Pull request by rejas**
node-zopfli is not building right now and seems to be not maintained anymore. so lets use the working imagemin solution for zopfli.

### CODE REVIEW

**Comment by rejas** [comment]
@patrickkettner I am still trying to get the page running on my local environment. The download page is still giving me trouble regarding the _.map function (see https://github.com/Modernizr/modernizr-neue/issues/72) Any ideas or is it working on your machine?

**Comment by patrickkettner** [comment]
it is working on mine, I haven't had time to dig into why it would be failing otherplaces :(

**Comment by rejas** [comment]
weird... what is your config (os, node, npm)?

**Comment by patrickkettner** [comment]
windows 10, node 10, whatever latest npm is today
also working on my mojave box with node 8

**Comment by rejas** [comment]
here its a mac os with node 10.4.1, npm 6.10, bower 1.8.4, doing a fresh install with cleaned caches, running `npm install`,` bower isntall` and then `npm run develop`. new issue maybe for figuring it out?

**Comment by rejas** [comment]
Opened a new issue for that in https://github.com/Modernizr/modernizr-neue/issues/128
Maybe this can be merged though @patrickkettner  ?

**Pull request merged**
