### PR TITLE
Update Modernizr branding

### PR DESCRIPTION
**Pull request by KuraFire**
- New logo, as well as new favicon
- original ModernizrPink color
- three bars in “hamburger” icon updated accordingly, to match

### CODE REVIEW

**Comment by KuraFire** [comment]
New logo looks like:

modernizr logo

**Comment by KuraFire** [comment]
@patrickkettner look good?

**Comment by patrickkettner** [comment]
whoop, sorry. forgot to actually release it. updated and live now

**Comment by patrickkettner** [comment]
great job!

**Comment by paulirish** [comment]
👍

**Pull request merged**
