### PR TITLE
Fix Travis `node_js` version to 4.7.0

### PR DESCRIPTION
**Pull request by toptalo**
There are some Error in Travis CI config

### CODE REVIEW

**Comment by rejas** [comment]
Maybe we should already go up to node v6 (node4 has reached its EOL), can you update your PR?
But where can we see the travis build status? https://travis-ci.org/Modernizr/modernizr-neue/ tells me this repo is not active in travis @patrickkettner ?

**Comment by toptalo** [comment]
If icon issue fixed in #125 why to update this PR. maybe just close?

**Comment by rejas** [comment]
This PR is about travis, not about the icons. And Node4 is not maintained anymore. So thats why I asked you to update the PR

**Comment by toptalo** [comment]
Added 6,8,10 node versions to `travis.yml`. But it seems like Travis is not used here

**Pull request merged**
